### ISSUE TITLE
Future tasks for Autonomous

### ISSUE THREAD

**Issue by SebZanardo** [thedropbears/pycrescendo#102]
```[tasklist]
### Tasks
- [x] Interface with components
- [x] Handle case if target note is not present
- [ ] Test and hardcode proper offsets for notes near stage legs
- [x] Add more Auto routines
- [x] Split routines and base autonomous logic into separate file
```
